# Local Intelligence Loader
# This file is automatically generated from rules/iocs.txt.
# DO NOT EDIT THIS FILE MANUALLY.

# The Intel Framework will read the file defined in local.zeek
# This file just needs to exist for the framework to initialize correctly.