%YAML 1.1
---
default-rule-path: /etc/suricata/rules
rule-files:
  - snort.rules

vars:
  address-groups:
    HOME_NET: "[192.168.0.0/16,10.0.0.0/8,172.16.0.0/12]"
    EXTERNAL_NET: "any"

eve-log:
  enabled: yes
  filetype: regular
  filename: eve.json
  types:
    - alert